branch-defaults:
  default:
    environment: null
global:
  application_name: oakcrime
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 18.06.1-ce
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
